# string
a = "Hello World"
#display a:
print(a)
#display the data type of a:
print(type(a)) 

# int
b = 20
#display b:
print(b)
#display the data type of b:
print(type(b)) 

# float
c = 20.5
#display c:
print(c)
#display the data type of c:
print(type(c)) 

# complex
d = 1j
#display d:
print(d)
#display the data type of d:
print(type(d)) 

# list
e = ["apple", "banana", "cherry"]
#display e:
print(e)
#display the data type of e:
print(type(e)) 

# tuple
f = ("apple", "banana", "cherry")
#display f:
print(f)
#display the data type of f:
print(type(f)) 

# range
g = range(10)
#display g:
print(g)
#convert to list to display the content of g:
print(list(g))

# dictionary
h = {"name" : "John", "age" : 36}
#display h:
print(h)
#display the data type of h:
print(type(h)) 

# set
i = {"apple", "banana", "cherry"}
#display i:
print(i)
#display the data type of i:
print(type(i)) 



